# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Build
  branches:
    include:
    - main
  always: true

pool: sonic-mirror-westus2-2
variables:
- group: SONiC-Azure-Key-Vault
- group: Debian-Mirror-Common
- group: SONiC-Mirror-US-West2-1
- name: StorageAccount
  value: 'sonicstoragepublic0'
- name: StorageAccountSasToken
  value: $(sonicstoragepublic0-SasToken)
- name: StorageAccountReplica
  value: 'sonicstoragepublic1'
- name: StorageAccountReplicaSasToken
  value: $(sonicstoragepublic1-SasToken)

stages:
- template: ../templates/debian-mirror-stages.yml
