parameters:
- name: 'mirrorName'
  type: string
  default: 'none'
- name: 'workspace'
  type: string
  default: 'work'
steps:
- bash: |
    set -e
    WORKSPACE=${{ parameters.workspace }}
    MIRROR_NAME=${{ parameters.mirrorName }}
    NFS_MOUNT_POINT=/nfs-$(StorageAccountNfs)-data
    NFS_MIRROR_POOL=$NFS_MOUNT_POINT/aptly/$MIRROR_NAME/pool
    PUBLISH_STORAGE=$(StorageAccount)
    [ "$(PublishToReplica)" == "y" ] && PUBLISH_STORAGE=$(StorageAccountReplica)
    STORAGE_PUBLISH_PATH=/blobfus-${PUBLISH_STORAGE}-web

    echo "Mount azure storage NFS 3.0"
    [ ! -d $NFS_MOUNT_POINT ] && sudo mkdir -p $NFS_MOUNT_POINT
    if mountpoint $NFS_MOUNT_POINT; then
      sudo umount $NFS_MOUNT_POINT
    fi

    sudo mount -o sec=sys,vers=3,nolock,proto=tcp $(StorageAccountNfs).blob.core.windows.net:/$(StorageAccountNfs)/data $NFS_MOUNT_POINT
    sudo chmod 777 $NFS_MOUNT_POINT

    echo "Mount storage"
    azure-pipelines/scripts/mirror/mount-storage.sh "/blobfuse-$(StorageAccount)-data" "$(StorageAccount)" "data" "/data/blobfuse-${StorageAccount}-data" y

    echo "Mount storage replica"
    azure-pipelines/scripts/mirror/mount-storage.sh "$STORAGE_PUBLISH_PATH" "$PUBLISH_STORAGE" '$web' "/data/blobfuse-${PUBLISH_STORAGE}-web" y
    

    echo "Clean up workspace"
    [ -e "$WORKSPACE" ] && sudo rm -rf "$WORKSPACE"

    echo 'Make nfs pool link'
    mkdir -p "$WORKSPACE"
    mkdir -p "$NFS_MIRROR_POOL"
    ln -s $NFS_MOUNT_POINT/aptly $WORKSPACE/_aptly
    ln -s $NFS_MIRROR_POOL $WORKSPACE/pool

    echo 'Make storage data link'
    ln -s /blobfuse-$(StorageAccount)-data $WORKSPACE/_storage_data

    echo 'Make storage publish link'
    ln -s $STORAGE_PUBLISH_PATH/debian $WORKSPACE/publish
  displayName: 'Mount nfs & storages'
